name: Fix SonarCloud Issues with Pixeebot
name: Pixeebot Activity Dashboard
on:
  schedule:
on:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
  check_run:
jobs:
  activity-dashboard:
    runs-on: ubuntu-latest
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
    types: [completed]
          projectKey: ${{ secrets.SONARCLOUD_PROJECT_KEY }}
          organization: ${{ secrets.SONARCLOUD_ORGANIZATION }}
          token: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: Process SonarCloud Results
        run: node dashboard/backend/processSonarResults.js
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:

          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run Pixeebot
        run: npm run pixeebot
      - name: Upload results
permissions:
        uses: actions/upload-artifact@v2
        with:
          name: pixeebot-results
  id-token: write

jobs:
  share:
    name: Upload Sonar Results to Pixeebot
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: pixee/upload-tool-results-action@v2
        with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
